#!/usr/bin/env zsh
# coding=utf-8
# Created by alan on 2023-07-16 02:30:13
# $pwd=**/website

# Set github account/email
set_github_env 2 &>/dev/null

# Branch name
local branch=gh-pages

# Command line parameter $1
# The default package generates an upload script,
# which is built and automatically uploaded when it is equal to bp.
local push_key=bp

echo "[$(date +'%F %T')]" 'Start Publish...'
(
    yarn &&
        yarn pub-all &&
        echo "Switch to "$branch"" &&
        git switch -c "$branch" ||
        git switch "$branch" &&
        echo sleep 10s && (
        local count=10
        while true; do
            if (git branch --show-current | grep -w "$branch"); then
                break
            fi
            sleep 0.5
            count=$((count + 1))
            echo $count
            if [ $count -ge 20 ]; then
                break
            fi
        done

    ) &&
        print '\e[33m'Removing current old project directory files...'\e[0m' &&
        find . -type d ! -path "./.git*" ! -path "./build*" ! -path "./node_modules*" -maxdepth 1 | grep -E './[^./]*$' | awk '{print $1}' | xargs rm -rf &&
        find . -type f ! -path "./.git*" ! -path "./build*" -maxdepth 1 | xargs rm -rf &&
        mv build/* . && rm -d build && (
        push_cmd="git add . && git commit -m '[$(date +'%F %T')] update: gh-pages (Automatic push)' && git push origin $branch" &&
            echo $1 | grep -w "$push_key" && $push_cmd ||
            (
                local push='./pushmycode' &&
                    rm $push 2 &>/dev/null ||
                    echo '#''!/usr/bin/env bash' >>$push &&
                    echo $push_cmd >>$push &&
                    echo chmod +x $push &&
                    print 'Run>>' '\e[1;33m'chmod +x $push '&&' $push'\e[0m' or '\e[1;33m'$push '\e[0m'to push your code.
            )
    )
) &&
    print '* \e[32m'Automatic build successful!'\e[0m' ||
    print '* \e[31m'Automatic build failed!'\e[0m'
